// client/src/app/components/admin/userslist/userslist.component.ts
import { Component, EventEmitter, Input, Output, OnInit } from '@angular/core';
import { CommonModule, NgIf, NgFor, NgClass } from '@angular/common';
import { FormBuilder } from '@angular/forms';
import { UserCreateModalComponent } from '../usercreatemodal/usercreatemodal.component';

@Component({
  selector: 'app-users-list',
  standalone: true,
  imports: [CommonModule, NgIf, NgFor, NgClass, UserCreateModalComponent],
  templateUrl: './userslist.component.html',
  styleUrls: ['./userslist.component.css']
})
export class UsersListComponent implements OnInit {
  @Input() users: any[] = [];
  @Output() selectUser = new EventEmitter<any>();

  loading = true;
  showCreateModal = false;

  constructor(private fb: FormBuilder) {}

  ngOnInit() {
    this.fetchUsers();
  }

  async fetchUsers() {
    try {
      this.loading = true;
      const response = await fetch(`${(window as any).env?.VITE_BACKEND_URL || ''}/api/users`);
      const data = await response.json();
      this.users = data;
    } catch (error) {
      console.error('Error fetching users:', error);
    } finally {
      this.loading = false;
    }
  }

  openCreateModal() {
    this.showCreateModal = true;
  }

  closeCreateModal() {
    this.showCreateModal = false;
  }

  handleUserCreated() {
    this.closeCreateModal();
    this.fetchUsers();
  }

  handleSelectUser(user: any) {
    this.selectUser.emit(user);
  }

  async toggleUserStatus(user: any, checked: boolean) {
    const token = localStorage.getItem('token');
    const action = checked ? 'unblock' : 'block';
    try {
      const res = await fetch(`${(window as any).env?.VITE_BACKEND_URL || ''}/api/block/${user.id}/${action}`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        }
      });
      if (!res.ok) throw new Error('No se pudo cambiar el estado');
      this.users = this.users.map(u => u.id === user.id ? { ...u, status: checked ? 'active' : 'inactive' } : u);
    } catch {
      alert('Error al cambiar el estado del usuario');
    }
  }
  getChecked(event: Event): boolean {
    return !!(event.target && (event.target as HTMLInputElement).checked);
  }
}

<div class="bg-white rounded-lg shadow">
  <div class="px-6 py-4 border-b border-gray-200">
    <div class="flex justify-between items-center mb-4">
      <div>
        <h2 class="text-lg font-semibold text-gray-900">Lista de Usuarios</h2>
        <p class="text-sm text-gray-600 mt-1">
          Total de usuarios: <span class="font-medium">{{ users.length }}</span>
        </p>
      </div>
      <button
        class="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 transition-colors text-sm font-medium"
        (click)="openCreateModal()"
      >
        + Agregar usuario
      </button>
    </div>
  </div>
  <app-user-create-modal
    [open]="showCreateModal"
    (onClose)="closeCreateModal()"
    (onSuccess)="handleUserCreated()"
  ></app-user-create-modal>
  <div class="overflow-x-auto p-6">
    <table class="min-w-full divide-y divide-gray-200 display">
      <thead>
        <tr>
          <th>ID</th>
          <th>Usuario</th>
          <th>Email</th>
          <th>Estado</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let user of users">
          <td>{{ user.id }}</td>
          <td>
            <div class="flex items-center">
              <img class="h-8 w-8 rounded-full object-cover" [src]="user.image || '/placeholder.svg?height=32&width=32'" [alt]="user.firstName || user.email" />
              <div class="ml-3">
                <div class="text-sm font-medium text-gray-900">{{ (user.firstName || '') + ' ' + (user.lastName || '') || user.email }}</div>
              </div>
            </div>
          </td>
          <td>{{ user.email }}</td>
          <td>
            <ng-container *ngIf="user.role !== 'admin'; else badgeOnly">
              <label class="relative inline-flex items-center cursor-pointer mr-3">
                <input type="checkbox" class="sr-only peer user-status-switch" [checked]="user.status === 'active'" (change)="toggleUserStatus(user, getChecked($event))" />
                <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
              </label>
              <span [ngClass]="user.status === 'active' ? 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800' : 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800'">
                {{ user.status === 'active' ? 'Activo' : 'Inactivo' }}
              </span>
            </ng-container>
            <ng-template #badgeOnly>
              <span [ngClass]="user.status === 'active' ? 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800' : 'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800'">
                {{ user.status === 'active' ? 'Activo' : 'Inactivo' }}
              </span>
            </ng-template>
          </td>
          <td>
            <button class="text-blue-600 hover:text-blue-900 transition-colors ver-detalles-btn" (click)="handleSelectUser(user)">Ver detalles</button>
          </td>
        </tr>
      </tbody>
    </table>
    <div *ngIf="loading" class="animate-pulse mt-4">
      <div class="h-4 bg-gray-200 rounded w-1/4 mb-4"></div>
      <div class="space-y-3">
        <div *ngFor="let i of [1,2,3,4,5]" class="h-4 bg-gray-200 rounded"></div>
      </div>
    </div>
  </div>
</div>

// client/src/components/admin/UsersList.jsx
import { useState, useEffect } from "react"

export default function UsersList({ onSelectUser }) {
  const [users, setUsers] = useState([])
  const [loading, setLoading] = useState(true)
  const [searchTerm, setSearchTerm] = useState("")

  useEffect(() => {
    fetchUsers()
  }, [])

  const fetchUsers = async () => {
    try {
      setLoading(true)
      const response = await fetch(`${import.meta.env.VITE_BACKEND_URL}/api/users`)
      const data = await response.json()
      setUsers(data)
    } catch (error) {
      console.error("Error fetching users:", error)
    } finally {
      setLoading(false)
    }
  }

  const filteredUsers = users.filter(
    (user) =>
      (user.firstName || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
      (user.lastName || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
      user.email.toLowerCase().includes(searchTerm.toLowerCase()),
  )

  // Cambiar estado activo/inactivo
  const handleToggleUserStatus = async (user) => {
    const token = localStorage.getItem('token');
    const action = user.status === 'active' ? 'block' : 'unblock';
    try {
      const res = await fetch(`${import.meta.env.VITE_BACKEND_URL}/api/block/${user.id}/${action}`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        }
      });
      if (!res.ok) throw new Error('No se pudo cambiar el estado');
      setUsers((prevUsers) =>
        prevUsers.map((u) =>
          u.id === user.id ? { ...u, status: user.status === 'active' ? 'inactive' : 'active' } : u
        )
      );
    } catch {
      alert('Error al cambiar el estado del usuario');
    }
  };

  if (loading) {
    return (
      <div className="bg-white rounded-lg shadow p-6">
        <div className="animate-pulse">
          <div className="h-4 bg-gray-200 rounded w-1/4 mb-4"></div>
          <div className="space-y-3">
            {[...Array(5)].map((_, i) => (
              <div key={i} className="h-4 bg-gray-200 rounded"></div>
            ))}
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="bg-white rounded-lg shadow">
      <div className="px-6 py-4 border-b border-gray-200">
        <div className="flex justify-between items-center mb-4">
          <div>
            <h2 className="text-lg font-semibold text-gray-900">Lista de Usuarios</h2>
            <p className="text-sm text-gray-600 mt-1">
              Total de usuarios: <span className="font-medium">{users.length}</span>
            </p>
          </div>
          <button className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 transition-colors text-sm font-medium">
            + Agregar usuario
          </button>
        </div>

        {/* Buscador */}
        <div className="relative">
          <input
            type="text"
            placeholder="Buscar usuarios..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
          />
          <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <svg className="h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
              />
            </svg>
          </div>
        </div>
      </div>

      {/* Tabla */}
      <div className="overflow-x-auto">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">ID</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Usuario
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Email</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Estado</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Acciones
              </th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {filteredUsers.map((user) => (
              <tr key={user.id} className="hover:bg-gray-50">
                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{user.id}</td>
                <td className="px-6 py-4 whitespace-nowrap">
                  <div className="flex items-center">
                    <img
                      className="h-8 w-8 rounded-full object-cover"
                      src={user.image || "/placeholder.svg?height=32&width=32"}
                      alt={user.firstName || user.email}
                    />
                    <div className="ml-3">
                      <div className="text-sm font-medium text-gray-900">
                        {(user.firstName || '') + ' ' + (user.lastName || '') || user.email}
                      </div>
                    </div>
                  </div>
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{user.email}</td>
                <td className="px-6 py-4 whitespace-nowrap">
                  <div className="flex items-center">
                    <label className="relative inline-flex items-center cursor-pointer mr-3">
                      <input
                        type="checkbox"
                        checked={user.status === 'active'}
                        onChange={() => handleToggleUserStatus(user)}
                        className="sr-only peer"
                      />
                      <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
                    </label>
                    <span
                      className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                        user.status === 'active' ? "bg-green-100 text-green-800" : "bg-red-100 text-red-800"
                      }`}
                    >
                      {user.status === 'active' ? "Activo" : "Inactivo"}
                    </span>
                  </div>
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                  <button
                    onClick={() => onSelectUser && onSelectUser(user)}
                    className="text-blue-600 hover:text-blue-900 transition-colors"
                  >
                    Ver detalles
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {filteredUsers.length === 0 && (
        <div className="text-center py-8">
          <p className="text-gray-500">No se encontraron usuarios</p>
        </div>
      )}
    </div>
  )
}
