// client/src/components/Footer.jsx
import { useState } from "react"

const Footer = () => {
  const [email, setEmail] = useState("")
  const currentYear = new Date().getFullYear()

  const handleNewsletterSubmit = (e) => {
    e.preventDefault()
    console.log("Newsletter subscription:", email)
    setEmail("")
  }

  return (
    <footer
      className="photography-footer"
      style={{ background: 'var(--color-primary)', color: 'var(--color-text)' }}
    >
      {/* Main Footer Content */}
      <div className="footer-container" style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', gap: '2rem', padding: '3rem 2rem 2rem 2rem', background: 'var(--color-primary)', color: 'var(--color-text)' }}>
        {/* Brand Information */}
        <div className="footer-brand" style={{ flex: '1 1 220px', minWidth: 220, marginBottom: '2rem' }}>
          <div className="brand-title" style={{ marginBottom: '0.5rem' }}>
            <p className="brand-main" style={{ fontWeight: 700, fontSize: '1.5rem', letterSpacing: 2, color: 'var(--color-accent)' }}>PHOTOGRAPHY</p>
            <p className="brand-sub" style={{ fontWeight: 500, fontSize: '1.1rem', color: 'var(--color-neutral)' }}>BY LANDING</p>
          </div>
          <p className="brand-description" style={{ color: 'var(--color-text)', marginBottom: '1rem' }}>Capturing special moments with art and passion.</p>

          <div className="social-links" style={{ display: 'flex', gap: '1rem', marginTop: '1rem' }}>
            <a href="#" className="social-icon" aria-label="Instagram" style={{ color: 'var(--color-accent)', fontSize: '1.5rem', transition: 'color 0.2s' }}>
              <i className="fab fa-instagram"></i>
            </a>
            <a href="#" className="social-icon" aria-label="LinkedIn" style={{ color: 'var(--color-accent)', fontSize: '1.5rem', transition: 'color 0.2s' }}>
              <i className="fab fa-linkedin"></i>
            </a>
            <a href="#" className="social-icon" aria-label="Facebook" style={{ color: 'var(--color-accent)', fontSize: '1.5rem', transition: 'color 0.2s' }}>
              <i className="fab fa-facebook"></i>
            </a>
            <a href="#" className="social-icon" aria-label="Dribbble" style={{ color: 'var(--color-accent)', fontSize: '1.5rem', transition: 'color 0.2s' }}>
              <i className="fab fa-dribbble"></i>
            </a>
          </div>
        </div>

        {/* Quick Links */}
        <div className="footer-section" style={{ flex: '1 1 180px', minWidth: 180, marginBottom: '2rem' }}>
          <h3 className="section-title" style={{ color: 'var(--color-accent)', fontWeight: 600, marginBottom: '1rem' }}>Quick Links</h3>
          <ul className="footer-links" style={{ listStyle: 'none', padding: 0 }}>
            <li><a href="#" className="footer-link" style={{ color: 'var(--color-text)', textDecoration: 'none', display: 'block', marginBottom: 6, transition: 'color 0.2s' }}>Home</a></li>
            <li><a href="#" className="footer-link" style={{ color: 'var(--color-text)', textDecoration: 'none', display: 'block', marginBottom: 6, transition: 'color 0.2s' }}>Portfolio</a></li>
            <li><a href="#" className="footer-link" style={{ color: 'var(--color-text)', textDecoration: 'none', display: 'block', marginBottom: 6, transition: 'color 0.2s' }}>Services</a></li>
            <li><a href="#" className="footer-link" style={{ color: 'var(--color-text)', textDecoration: 'none', display: 'block', marginBottom: 6, transition: 'color 0.2s' }}>About Me</a></li>
            <li><a href="#" className="footer-link" style={{ color: 'var(--color-text)', textDecoration: 'none', display: 'block', marginBottom: 6, transition: 'color 0.2s' }}>Contact</a></li>
            <li><a href="#" className="footer-link" style={{ color: 'var(--color-text)', textDecoration: 'none', display: 'block', marginBottom: 6, transition: 'color 0.2s' }}>Blog</a></li>
          </ul>
        </div>

        {/* Services */}
        <div className="footer-section" style={{ flex: '1 1 180px', minWidth: 180, marginBottom: '2rem' }}>
          <h3 className="section-title" style={{ color: 'var(--color-accent)', fontWeight: 600, marginBottom: '1rem' }}>Services</h3>
          <ul className="footer-links" style={{ listStyle: 'none', padding: 0 }}>
            <li><a href="#" className="footer-link" style={{ color: 'var(--color-text)', textDecoration: 'none', display: 'block', marginBottom: 6, transition: 'color 0.2s' }}>Wedding Photography</a></li>
            <li><a href="#" className="footer-link" style={{ color: 'var(--color-text)', textDecoration: 'none', display: 'block', marginBottom: 6, transition: 'color 0.2s' }}>Portrait Sessions</a></li>
            <li><a href="#" className="footer-link" style={{ color: 'var(--color-text)', textDecoration: 'none', display: 'block', marginBottom: 6, transition: 'color 0.2s' }}>Product Photography</a></li>
            <li><a href="#" className="footer-link" style={{ color: 'var(--color-text)', textDecoration: 'none', display: 'block', marginBottom: 6, transition: 'color 0.2s' }}>Corporate Events</a></li>
            <li><a href="#" className="footer-link" style={{ color: 'var(--color-text)', textDecoration: 'none', display: 'block', marginBottom: 6, transition: 'color 0.2s' }}>Family Sessions</a></li>
            <li><a href="#" className="footer-link" style={{ color: 'var(--color-text)', textDecoration: 'none', display: 'block', marginBottom: 6, transition: 'color 0.2s' }}>Aerial Photography</a></li>
          </ul>
        </div>

        {/* Contact Information */}
        <div className="footer-section" style={{ flex: '1 1 220px', minWidth: 220, marginBottom: '2rem' }}>
          <h3 className="section-title" style={{ color: 'var(--color-accent)', fontWeight: 600, marginBottom: '1rem' }}>Contact Us</h3>
          <address className="contact-info" style={{ fontStyle: 'normal', color: 'var(--color-text)' }}>
            <div className="contact-item" style={{ display: 'flex', alignItems: 'center', marginBottom: 6 }}>
              <i className="fas fa-map-marker-alt contact-icon" style={{ color: 'var(--color-neutral)', marginRight: 8 }}></i>
              <span style={{ color: 'var(--color-text)' }}>123 Photography Street, Image City</span>
            </div>
            <div className="contact-item" style={{ display: 'flex', alignItems: 'center', marginBottom: 6 }}>
              <i className="fas fa-phone contact-icon" style={{ color: 'var(--color-neutral)', marginRight: 8 }}></i>
              <a href="tel:+1234567890" className="footer-link" style={{ color: 'var(--color-text)', textDecoration: 'none' }}>+1 234 567 890</a>
            </div>
            <div className="contact-item" style={{ display: 'flex', alignItems: 'center', marginBottom: 6 }}>
              <i className="fas fa-envelope contact-icon" style={{ color: 'var(--color-neutral)', marginRight: 8 }}></i>
              <a href="mailto:info@landingphotography.com" className="footer-link" style={{ color: 'var(--color-text)', textDecoration: 'none' }}>info@landingphoto.com</a>
            </div>
            <div className="contact-item" style={{ display: 'flex', alignItems: 'center', marginBottom: 6 }}>
              <i className="fas fa-clock contact-icon" style={{ color: 'var(--color-neutral)', marginRight: 8 }}></i>
              <span style={{ color: 'var(--color-text)' }}>Mon-Fri: 9:00 AM - 6:00 PM</span>
            </div>
          </address>

          {/* Newsletter Subscription */}
          <div className="newsletter" style={{ marginTop: '1.5rem' }}>
            <h4 className="newsletter-title" style={{ color: 'var(--color-accent)', fontWeight: 500, marginBottom: 8 }}>Subscribe to our newsletter</h4>
            <form className="newsletter-form" onSubmit={handleNewsletterSubmit} style={{ display: 'flex', gap: 8 }}>
              <input
                type="email"
                placeholder="Your email"
                className="newsletter-input"
                aria-label="Email for newsletter subscription"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
                style={{
                  flex: 1,
                  padding: '0.5rem 1rem',
                  borderRadius: 6,
                  border: '1px solid var(--color-neutral)',
                  background: 'var(--color-secondary)',
                  color: 'var(--color-text)',
                  outline: 'none',
                  fontSize: '1rem',
                  marginRight: 4
                }}
              />
              <style>{`
                .newsletter-input::placeholder {
                  color: var(--color-text);
                  opacity: 1;
                }
              `}</style>
              <button
                type="submit"
                className="newsletter-button"
                aria-label="Subscribe"
                style={{
                  background: 'var(--color-accent)',
                  color: 'var(--color-secondary)',
                  border: 'none',
                  borderRadius: 6,
                  padding: '0.5rem 1rem',
                  cursor: 'pointer',
                  fontSize: '1.2rem',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  transition: 'background 0.2s'
                }}
              >
                <i className="fas fa-paper-plane"></i>
              </button>
            </form>
          </div>
        </div>
      </div>

      {/* Copyright and Legal */}
      <div className="copyright-section" style={{ background: 'var(--color-accent)', color: 'var(--color-text)', padding: '1rem 2rem' }}>
        <div className="copyright-container" style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: '1rem' }}>
          <div className="copyright-text" style={{ fontSize: '1rem', color: 'var(--color-text)' }}>&copy; {currentYear} Landing Photography. All rights reserved.</div>
          <div className="legal-links" style={{ display: 'flex', gap: '1.5rem' }}>
            <a href="#" className="legal-link" style={{ color: 'var(--color-text)', textDecoration: 'underline', fontSize: '1rem' }}>Privacy Policy</a>
            <a href="#" className="legal-link" style={{ color: 'var(--color-text)', textDecoration: 'underline', fontSize: '1rem' }}>Terms of Service</a>
            <a href="#" className="legal-link" style={{ color: 'var(--color-text)', textDecoration: 'underline', fontSize: '1rem' }}>Cookie Policy</a>
          </div>
        </div>
      </div>
    </footer>
  )
}

export default Footer

// client/src/app/components/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  standalone: true,
  template: `
    <footer
      class="photography-footer"
      style="background: var(--color-primary); color: var(--color-text);"
    >
      <div class="footer-container" style="display: flex; flex-wrap: wrap; justify-content: space-between; gap: 2rem; padding: 3rem 2rem 2rem 2rem; background: var(--color-primary); color: var(--color-text);">
        <div class="footer-brand" style="flex: 1 1 220px; min-width: 220px; margin-bottom: 2rem;">
          <div class="brand-title" style="margin-bottom: 0.5rem;">
            <p class="brand-main" style="font-weight: 700; font-size: 1.5rem; letter-spacing: 2px; color: var(--color-accent);">PHOTOGRAPHY</p>
            <p class="brand-sub" style="font-weight: 500; font-size: 1.1rem; color: var(--color-neutral);">BY LANDING</p>
          </div>
          <p class="brand-description" style="color: var(--color-text); margin-bottom: 1rem;">Capturing special moments with art and passion.</p>
          <div class="social-links" style="display: flex; gap: 1rem; margin-top: 1rem;">
            <a href="#" class="social-icon" aria-label="Instagram" style="color: var(--color-accent); font-size: 1.5rem; transition: color 0.2s;"><i class="fab fa-instagram"></i></a>
            <a href="#" class="social-icon" aria-label="LinkedIn" style="color: var(--color-accent); font-size: 1.5rem; transition: color 0.2s;"><i class="fab fa-linkedin"></i></a>
            <a href="#" class="social-icon" aria-label="Facebook" style="color: var(--color-accent); font-size: 1.5rem; transition: color 0.2s;"><i class="fab fa-facebook"></i></a>
            <a href="#" class="social-icon" aria-label="Dribbble" style="color: var(--color-accent); font-size: 1.5rem; transition: color 0.2s;"><i class="fab fa-dribbble"></i></a>
          </div>
        </div>
        <div class="footer-section" style="flex: 1 1 180px; min-width: 180px; margin-bottom: 2rem;">
          <h3 class="section-title" style="color: var(--color-accent); font-weight: 600; margin-bottom: 1rem;">Quick Links</h3>
          <ul class="footer-links" style="list-style: none; padding: 0;">
            <li><a href="#" class="footer-link" style="color: var(--color-text); text-decoration: none; display: block; margin-bottom: 6px; transition: color 0.2s;">Home</a></li>
            <li><a href="#" class="footer-link" style="color: var(--color-text); text-decoration: none; display: block; margin-bottom: 6px; transition: color 0.2s;">Portfolio</a></li>
            <li><a href="#" class="footer-link" style="color: var(--color-text); text-decoration: none; display: block; margin-bottom: 6px; transition: color 0.2s;">Services</a></li>
            <li><a href="#" class="footer-link" style="color: var(--color-text); text-decoration: none; display: block; margin-bottom: 6px; transition: color 0.2s;">About Me</a></li>
            <li><a href="#" class="footer-link" style="color: var(--color-text); text-decoration: none; display: block; margin-bottom: 6px; transition: color 0.2s;">Contact</a></li>
            <li><a href="#" class="footer-link" style="color: var(--color-text); text-decoration: none; display: block; margin-bottom: 6px; transition: color 0.2s;">Blog</a></li>
          </ul>
        </div>
        <div class="footer-section" style="flex: 1 1 180px; min-width: 180px; margin-bottom: 2rem;">
          <h3 class="section-title" style="color: var(--color-accent); font-weight: 600; margin-bottom: 1rem;">Services</h3>
          <ul class="footer-links" style="list-style: none; padding: 0;">
            <li><a href="#" class="footer-link" style="color: var(--color-text); text-decoration: none; display: block; margin-bottom: 6px; transition: color 0.2s;">Wedding Photography</a></li>
            <li><a href="#" class="footer-link" style="color: var(--color-text); text-decoration: none; display: block; margin-bottom: 6px; transition: color 0.2s;">Portrait Sessions</a></li>
            <li><a href="#" class="footer-link" style="color: var(--color-text); text-decoration: none; display: block; margin-bottom: 6px; transition: color 0.2s;">Product Photography</a></li>
            <li><a href="#" class="footer-link" style="color: var(--color-text); text-decoration: none; display: block; margin-bottom: 6px; transition: color 0.2s;">Corporate Events</a></li>
            <li><a href="#" class="footer-link" style="color: var(--color-text); text-decoration: none; display: block; margin-bottom: 6px; transition: color 0.2s;">Family Sessions</a></li>
            <li><a href="#" class="footer-link" style="color: var(--color-text); text-decoration: none; display: block; margin-bottom: 6px; transition: color 0.2s;">Aerial Photography</a></li>
          </ul>
        </div>
        <div class="footer-section" style="flex: 1 1 220px; min-width: 220px; margin-bottom: 2rem;">
          <h3 class="section-title" style="color: var(--color-accent); font-weight: 600; margin-bottom: 1rem;">Contact Us</h3>
          <address class="contact-info" style="font-style: normal; color: var(--color-text);">
            <div class="contact-item" style="display: flex; align-items: center; margin-bottom: 6px;"><i class="fas fa-map-marker-alt contact-icon" style="color: var(--color-neutral); margin-right: 8px;"></i><span style="color: var(--color-text);">123 Photography Street, Image City</span></div>
            <div class="contact-item" style="display: flex; align-items: center; margin-bottom: 6px;"><i class="fas fa-phone contact-icon" style="color: var(--color-neutral); margin-right: 8px;"></i><a href="tel:+1234567890" class="footer-link" style="color: var(--color-text); text-decoration: none;">+1 234 567 890</a></div>
            <div class="contact-item" style="display: flex; align-items: center; margin-bottom: 6px;"><i class="fas fa-envelope contact-icon" style="color: var(--color-neutral); margin-right: 8px;"></i><a href="mailto:info@landingphotography.com" class="footer-link" style="color: var(--color-text); text-decoration: none;">info@landingphoto.com</a></div>
            <div class="contact-item" style="display: flex; align-items: center; margin-bottom: 6px;"><i class="fas fa-clock contact-icon" style="color: var(--color-neutral); margin-right: 8px;"></i><span style="color: var(--color-text);">Mon-Fri: 9:00 AM - 6:00 PM</span></div>
          </address>
          <div class="newsletter" style="margin-top: 1.5rem;">
            <h4 class="newsletter-title" style="color: var(--color-accent); font-weight: 500; margin-bottom: 8px;">Subscribe to our newsletter</h4>
            <form class="newsletter-form" (submit)="handleNewsletterSubmit($event)" style="display: flex; gap: 8px;">
              <input
                type="email"
                placeholder="Your email"
                class="newsletter-input"
                aria-label="Email for newsletter subscription"
                [(ngModel)]="email"
                name="newsletterEmail"
                required
                style="flex: 1; padding: 0.5rem 1rem; border-radius: 6px; border: 1px solid var(--color-neutral); background: var(--color-secondary); color: var(--color-text); outline: none; font-size: 1rem; margin-right: 4px;"
              />
              <button
                type="submit"
                class="newsletter-button"
                aria-label="Subscribe"
                style="background: var(--color-accent); color: var(--color-secondary); border: none; border-radius: 6px; padding: 0.5rem 1rem; cursor: pointer; font-size: 1.2rem; display: flex; align-items: center; justify-content: center; transition: background 0.2s;"
              >
                <i class="fas fa-paper-plane"></i>
              </button>
            </form>
          </div>
        </div>
      </div>
      <div class="copyright-section" style="background: var(--color-accent); color: var(--color-text); padding: 1rem 2rem;">
        <div class="copyright-container" style="display: flex; flex-wrap: wrap; justify-content: space-between; align-items: center; gap: 1rem;">
          <div class="copyright-text" style="font-size: 1rem; color: var(--color-text);">&copy; {{ currentYear }} Landing Photography. All rights reserved.</div>
          <div class="legal-links" style="display: flex; gap: 1.5rem;">
            <a href="#" class="legal-link" style="color: var(--color-text); text-decoration: underline; font-size: 1rem;">Privacy Policy</a>
            <a href="#" class="legal-link" style="color: var(--color-text); text-decoration: underline; font-size: 1rem;">Terms of Service</a>
            <a href="#" class="legal-link" style="color: var(--color-text); text-decoration: underline; font-size: 1rem;">Cookie Policy</a>
          </div>
        </div>
      </div>
    </footer>
  `,
  imports: [],
  standalone: true
})
export class Footer {
  email = '';
  currentYear = new Date().getFullYear();

  handleNewsletterSubmit(event: Event) {
    event.preventDefault();
    console.log('Newsletter subscription:', this.email);
    this.email = '';
  }
}
